project:
  type: book

book:
  title: "Analyse de réseau avec Python et NetworkX"
  author: "Laurent Beauguitte"
  date: "07/13/2023"
  chapters:
    - index.qmd
    - C1_importer.qmd
    - C2_filtrer.qmd
    - C3_mesurer.qmd
    - C4_partitions.qmd
#   - C5_flot.qmd
    - C6_visualiser.qmd
    - conclusion.qmd
#   - summary.qmd
#    - references.qmd

bibliography: references.bib
lang: fr
csl: universite-de-montreal-apa.csl

toc-title: "Sommaire"
title-block-author-single: "Auteur"
title-block-published: "Mis en ligne le"
date-format: "DD MM YYYY"

format:
  html:
    theme: cosmo
  pdf:
    documentclass: scrreprt

editor: visual
