# Mesures

Les mesures sont testées sur deux réseaux, l'un orienté (`GD`) et l'autre non (`GU`), correspondant à la plus grande composante connexe. Lorsque la valuation et l'orientation des liens peuvent être prises en compte, les options utiles sont signalées. Par contre, le cas des liens multiples et des boucles n'est pas abordé.

`NetworkX` propose de nombreuses mesures et méthodes issues de la théorie des graphes au sens strict (centre, barycentre, rayon, etc.) et de l'analyse des flots dans les réseaux (optimisation) ; toutes ne sont pas évoquées ici et je me suis intéressé en priorité aux méthodes me semblant - peut-être à tort - les plus utilisées en sciences sociales.

```{python}
#| echo: false
import pandas as pd                # manipulation de tableaux
import networkx as nx              # analyse de réseau
import numpy as np                 # statistiques
import matplotlib.pyplot as plt    # visualisation
sommets = pd.read_csv("data/som_d13.csv", sep = ";")
liens = pd.read_csv("data/liens_d13.csv", sep = ";")
sommets[['CODGEO']] = sommets[['CODGEO']].astype('string')
sommets[['MARS']] = sommets[['MARS']].astype('bool')
liens[['Origine']] = liens[['Origine']].astype('string')
liens[['Arrivee']] = liens[['Arrivee']].astype('string')
G = nx.from_pandas_edgelist(liens,source = "Origine",target = "Arrivee", edge_attr="weight",create_using=nx.DiGraph()) 
nodes_attr = sommets.set_index('CODGEO').to_dict(orient = 'index')
nx.set_node_attributes(G, nodes_attr)
CC = sorted(nx.weakly_connected_components(G),key=len,reverse=True) 
GD = G.subgraph(CC[0])
GU = nx.create_empty_copy(GD, with_data=True)
GU = nx.to_undirected(GU)
list(list(GU.nodes(data=True))[0][-1].keys())
GU = nx.Graph(GU)
GU.add_edges_from(GD.edges(), weight=0)
for u, v, d in GD.edges(data=True):
    GU[u][v]['weight'] += d['weight']
```

## Mesures globales

Dans les pages précédentes, on a déjà vu comment afficher l'ordre et la taille du réseau. La densité s'obtient avec la fonction `density`, le diamètre avec la fonction `diameter`.

```{python}
# ordre et taille
print("nombre de sommets (ordre) : ", nx.number_of_nodes(GD), " sommets")
print("nombre de liens - orienté (taille) : ", nx.number_of_edges(GD), " liens")
print("nombre de sommets (ordre) : ", nx.number_of_nodes(GU), " sommets")
print("nombre de liens - non orienté (taille) : ", nx.number_of_edges(GU), " liens")

# densité et diamètre
print("densité (orienté) : ", round(nx.density(GD), 2))
print("densité (non orienté) :", round(nx.density(GU), 2))
# print("diamètre (non orienté et connexe) : ", nx.diameter(GD))
```

Si on cherche à mesurer le diamètre sur un réseau orienté non fortement connexe, on obtient le message d'erreur suivant : "Found infinite path length because the digraph is not strongly connected".

Mesures directement issues de la théorie des graphes, rayon et barycentre (appelé aussi point médian) correspondent respectivement à la distance entre le(s) sommet(s) ayant une excentricité minimale et tout autre sommet du graphe (cf *infra* les mesures locales) et à l'ensemble de sommets minimisant la fonction $\sum_{u \in V(G)} d_G(u, v)$, $d_G(u, v)$ étant la distance (topologique ou valuée) entre deux sommets $u$ et $v$ de $G$.

```{python}
# rayon
print("rayon : ", nx.radius(GU))

# barycentre
print("barycentre : ", nx.barycenter(GU))
print("barycentre (valué) : ", nx.barycenter(GU, weight='weight'))
```

La liste du ou des sommets centraux s'obtient avec `center`, la liste des sommets périphériques avec `periphery`. Les premiers correspondent aux sommets ayant une excentricité minimale, les seconds aux sommets ayant une excentricité maximale.

```{python}
print("Sommets centraux : ", nx.center(GU))
print("Sommets périphériques : ", nx.periphery(GU))
```

Comme toutes les mesures fondées sur la recherche de plus courts chemins (diamètre, rayon, etc.), ces fonctions supposent soit un réseau non orienté, soit un réseau orienté fortement connexe.

Il est possible de connaître l'ensemble des isthmes et des points d'articulation présents dans un réseau.

```{python}
# isthmes et points d'articulation (réseau connexe)
# nombre et liste des isthmes
print("nb isthmes : ", len(list(nx.bridges(GU))))
print("isthmes : ",list(nx.bridges(GU)))

# nombre et liste des points d'articulation
print("nb points d'articulation : ", len(list(nx.articulation_points(GU))))
print("points d'articulation : ", list(nx.articulation_points(GU)))
```

L'indice de Wiener, issu de l'étude des réseaux biologiques, correspond à la somme des plus courts chemins entre toutes les paires de sommets (équivaut à l'indice de dispersion de Shimbel parfois utilisé par les géographes des transports). Le réseau orienté n'étant pas fortement connexe, le résultat est une distance infinie (`inf`). Il est possible de prendre en compte la valuation des liens et de chercher la somme des plus courtes distances entre sommets.

```{python}
# indice de wiener (somme des pcc)
print("Indice de Wiener (orienté) : ", nx.wiener_index(GD))     # distance topologique
print("Indice de Wiener (non orienté) : ", nx.wiener_index(GU)) # distance topologique
print("Indice de Wiener (non orienté, valué) : ", nx.wiener_index(GU, 'weight'))  # somme des intensités
```

Mesure plus récente et liée davantage aux études des physiciennes sur les réseaux, l'assortativité est mesurée par défaut en fonction du degré. Elle varie entre -1 (réseau disassortatif, les sommets ayant un degré faible tendent à être voisins des sommets ayant un degré élevé et inversement) et 1 (réseau assortatif, les sommets ayant un degré faible sont voisins de sommets ayant un degré faible, les sommets ayant un degré élevé sont voisins de sommets ayant un degré élevé). Dans les lignes ci-dessous, les quatre assortativités possibles dans un réseau orienté sont calculées en fonction du degré.

```{python}
# assortativité (degré par défaut)
# réseau orienté - 4 options possibles
print("assortativité in-in : ", 
      round(nx.degree_assortativity_coefficient(GD, x="in", y='in'),3))

print("assortativité in-out : ", 
      round(nx.degree_assortativity_coefficient(GD, x="in", y='out'),3))

print("assortativité out-in : ", 
      round(nx.degree_assortativity_coefficient(GD, x="out", y='in'),3))

print("assortativité out-out : ", 
      round(nx.degree_assortativity_coefficient(GD, x="out", y='out'),3))

# réseau non orienté
print("assortativité globale (non orienté) : ", 
      round(nx.degree_assortativity_coefficient(GU),3))

# assortativité selon un critère autre que le degré
print(round(nx.numeric_assortativity_coefficient(GD, "MARS"),3))
```

Mesure relativement proche (voir la page [wikipedia](https://en.wikipedia.org/wiki/Rich-club_coefficient)), le `rich club coefficient` s'obtient avec la fonction... `rich_club_coefficient` ; elle peut être utilisée uniquement sur des réseaux non orientés et ne tient pas compte des éventuelles boucles, liens multiples ou intensité des liens. La fonction renvoie une valeur par degré (rc coefficient des sommets de degré 1, de degré 2, etc.).

```{python}
# rich-club coefficient
print("rich-club coefficient : ", nx.rich_club_coefficient(GU, normalized=True, seed=42))
```

Les mesures "globales" fondées sur des mesures "locales" (degré ou transitivité moyenne par exemple) sont abordées dans la section suivante.

## Mesures locales

Le degré se calcule à l'aide de la fonction `degree`. Si le réseau étudié est orienté, on peut utiliser `in_degree` et `out_degree`. L'argument optionnel `weight` permet de calculer le degré pondéré par l'intensité des liens.

```{python}
# degré
print(GD.degree())

#degré entrant, sortant
print(GD.in_degree())
print(GD.out_degree())

# degré entrant pondéré
print(GD.in_degree(weight = "weight"))
```

Ajouter `_centrality` à la fonction utilisée permet d'obtenir les valeurs normalisées.

```{python}
# degré normalisé
print(nx.degree_centrality(GD))
```

Pour transformer une mesure en attribut, on commence par créer un objet correspondondant au résultat puis on utilise la fonction `set_node_attributes` si la mesure porte sur les sommets et `set_edge_attributes` si elle porte sur les liens.

```{python}
# transformer une meure en attribut 
deg = nx.degree(GU)
nx.set_node_attributes(GU, 'degree', deg)
print("attribut des sommets : ", list(list(GU.nodes(data=True))[0][-1].keys()))
```

Les lignes ci-dessous proposent différentes solutions pour visualiser la distribution des degrés :

-   histogramme ;
-   fréquence ;
-   fréquence avec une échelle log-log.

<!-- https://networkx.org/documentation/stable/auto_examples/drawing/plot_degree.html -->

```{python}
# distribution sous forme d'histogramme
degree_in = sorted((d for n, d in GD.in_degree()), reverse=True)
plt.bar(*np.unique(degree_in, return_counts=True))
plt.title("Degrés entrants")
plt.xlabel("Degré")
plt.ylabel("Fréquence")

# fréquence
degree_sequence = sorted((d for n, d in GU.degree()), reverse=True)

# distribution des degrés
plt.plot(degree_sequence, "r-", marker="o", linewidth=1, markersize=2)
plt.title("Distribution des degrés")
plt.xlabel('Degré')
plt.ylabel('Fréquence')

# distribution degré - échelle log - log
plt.loglog(degree_sequence, "go-", linewidth=1, markersize=2)
plt.title("Distribution des degrés (log - log)")
plt.xlabel('Degré')
plt.ylabel('Fréquence')
```

Il est possible de calculer le degré moyen des voisins à à l'aide de la fonction `average_neighbor_degree` (degré entrant, sortant, total, pondéré ou non).

```{python}
# degré moyen des sommets voisins
nx.average_neighbor_degree(GD)
# degré entrant moyen des voisins entrants
nx.average_neighbor_degree(GD, source="in", target="in")
# degré moyen pondéré des voisins
nx.average_neighbor_degree(GD, weight="weight")
```

Les mesures de centralité autres s'obtiennent avec des fonctions aux noms attendus : `closeness`, `betweenness` (`edge_betweenness` pour l'intermédiarité des liens), `eigenvector_centrality` et `katz_centrality`.

```{python}
#| eval: false
# intermédiarité
nx.betweenness_centrality(GD)
L`` 
# intermédiarité des liens
nx.edge_betweenness_centrality(GD)

# proximité
nx.closeness_centrality(GD)

# centralité de vecteur propre
nx.eigenvector_centrality(GD)

# centralité de Katz
nx.katz_centrality(GD)
```

<!-- distance entre deux sommets : resistance_distance(G, nodeA, nodeB, weight=None, invert_weight=True)  si weight, distance; sinon, plus court chemin -->

Concernant la recherche de la transitivité, on peut connaître le nom de triangles (triades fermées) contenant chaque sommet avec la fonction `triangles`. La transitivité locale s'obtient avec `clustering`, la transitivité globale avec `transitivity` et la transitivité moyenne avec `average_clustering`. Il est possible de prendre en compte l'orientation des liens et/ou leur intensité.

```{python}
#| eval: false
# nombre de triangles
nx.triangles(GU)

# typologie MAN (réseau orienté)
nx.triadic_census(GD) 

# transitivité locale
nx.clustering(GD)

# prise en compte de l'intensité des liens
nx.clustering(GD, weight="weight")
```

```{python}

# transitivité globale et moyenne
print("Transitivité globale (orienté) : ", round(nx.transitivity(GD), 2))
print("Transitivité moyenne (orienté) : ", round(nx.average_clustering(GD), 2))
print("Transitivité globale (non orienté) : ", round(nx.transitivity(GU), 2))
print("Transitivité moyenne (non orienté) : ", round(nx.average_clustering(GU), 2))
```

<!-- v2 https://networkx.org/documentation/stable/reference/algorithms/centrality.html#second-order-centrality -->
<!-- contrainte de Burt : nx.constraint -->
